CREATE TABLE "cloud_providers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cloud_providers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"display_name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "cloud_providers_name_unique" UNIQUE("name")
);
ALTER TABLE "cloud_providers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
--> statement-breakpoint
ALTER TABLE "cloud_instances" ADD COLUMN "provider_id" bigint NOT NULL;--> statement-breakpoint
ALTER TABLE "cloud_instances" ADD CONSTRAINT "cloud_instances_provider_id_cloud_providers_id_fk" FOREIGN KEY ("provider_id") REFERENCES "public"."cloud_providers"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "cloud_instances" DROP COLUMN "provider";--> statement-breakpoint
DROP TYPE "public"."provider";