CREATE TYPE "public"."severity_level" AS ENUM('red', 'yellow', 'green');--> statement-breakpoint
CREATE TABLE "zkvm_performance_metrics" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zkvm_performance_metrics_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"zkvm_id" bigint NOT NULL,
	"size_bytes" bigint NOT NULL,
	"verification_ms" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "zkvm_performance_metrics_zkvm_id_unique" UNIQUE("zkvm_id")
);
--> statement-breakpoint
ALTER TABLE "zkvm_performance_metrics" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "zkvm_security_metrics" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zkvm_security_metrics_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"zkvm_id" bigint NOT NULL,
	"protocol_soundness" "severity_level" NOT NULL,
	"implementation_soundness" "severity_level" NOT NULL,
	"evm_stf_bytecode" "severity_level" NOT NULL,
	"quantum_security" "severity_level" NOT NULL,
	"security_target_bits" integer NOT NULL,
	"max_bounty_amount" bigint NOT NULL,
	"trusted_setup" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "zkvm_security_metrics_zkvm_id_unique" UNIQUE("zkvm_id")
);
--> statement-breakpoint
ALTER TABLE "zkvm_security_metrics" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "zkvm_performance_metrics" ADD CONSTRAINT "zkvm_performance_metrics_zkvm_id_zkvms_id_fk" FOREIGN KEY ("zkvm_id") REFERENCES "public"."zkvms"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "zkvm_security_metrics" ADD CONSTRAINT "zkvm_security_metrics_zkvm_id_zkvms_id_fk" FOREIGN KEY ("zkvm_id") REFERENCES "public"."zkvms"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "zkvm_performance_metrics" AS PERMISSIVE FOR SELECT TO public USING (true);--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "zkvm_security_metrics" AS PERMISSIVE FOR SELECT TO public USING (true);